<?php

/**
 * Edit apache2.conf to modify Apache default website
 *
 * @copyright   (C) 2015 Rain Lee <raincious@gmail.com>
 * @see         LICENSE for license
 */

define('CONFIG_FILE_DEFAULT', '/etc/apache2/sites-available/000-default.conf');
define('CONFIG_FILE_TOOL', '/etc/apache2/sites-available/000-tool.conf');
define('CONFIG_FILE_TEST', '/etc/apache2/sites-available/000-test.conf');

define('HOST_CONFIG_TEMPLATE', "<VirtualHost *:80>
\tServerName %{HOST_NAME}
\tServerAdmin webmaster@%{HOST_NAME}
\tDocumentRoot /var/www/%{PROJECT_DIR}
\tphp_flag xdebug.default_enable off
\tphp_flag xdebug.coverage_enable off
\tphp_flag xdebug.profiler_enable off
\tphp_flag xdebug.remote_enable off
\tErrorLog \${APACHE_LOG_DIR}/%{HOST_NAME}-error.log
\tCustomLog \${APACHE_LOG_DIR}/%{HOST_NAME}-access.log combined
</VirtualHost>

<IfModule mod_ssl.c>
\t<VirtualHost *:443>
\t\tServerName %{HOST_NAME}
\t\tServerAdmin webmaster@%{HOST_NAME}
\t\tDocumentRoot /var/www/%{PROJECT_DIR}
\t\tphp_flag xdebug.default_enable off
\t\tphp_flag xdebug.coverage_enable off
\t\tphp_flag xdebug.profiler_enable off
\t\tphp_flag xdebug.remote_enable off
\t\tSSLEngine On
\t\tSSLCertificateFile /etc/apache2/ssl/%{HOST_NAME}.crt
\t\tSSLCertificateKeyFile /etc/apache2/ssl/%{HOST_NAME}.key
\t\tErrorLog \${APACHE_LOG_DIR}/%{HOST_NAME}-error.log
\t\tCustomLog \${APACHE_LOG_DIR}/%{HOST_NAME}-access.log combined
\t</VirtualHost>
</IfModule>

# Generated By 3AX.ORG Vagrant VM Generater Script #\r\n");

require('LibApacheVirtualHostModifier.php');

if (empty($argv[1])) {
    exit(1);
}

exit(rewindApacheVirtualHostConfig(CONFIG_FILE_DEFAULT, array(
    '%{PROJECT_DIR}' => 'default',
    '%{HOST_NAME}' => $argv[1],
)) && createApacheVirtualHostConfig(CONFIG_FILE_TOOL, array(
    '%{PROJECT_DIR}' => 'tool',
    '%{HOST_NAME}' => 'tool.' . $argv[1],
)) && createApacheVirtualHostConfig(CONFIG_FILE_TEST, array(
    '%{PROJECT_DIR}' => 'test',
    '%{HOST_NAME}' => 'test.' . $argv[1],
)) ? 0 : 1);